site_name: Tensora
site_description: Sparse/dense tensor library for Python
site_author: David Hagen

repo_name: drhagen/tensora
repo_url: https://github.com/drhagen/tensora/
edit_uri: ''

copyright: >
  &copy; David R Hagen. Content available under an
  <a href="https://github.com/drhagen/tensora/blob/master/LICENSE">MIT license</a>.

theme:
  name: material

  icon:
    logo: fontawesome/solid/braille
    repo: fontawesome/brands/github

  palette:
    - scheme: default
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: yellow
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/drhagen
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/1485877/drhagen
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/drhagen
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/davidrhagen/

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Creation: creation.md
  - Tensors: tensors.md
  - Evaluate: evaluate.md
  - Contributing: contributing.md
